import {
  fontLato,
  fontLexendDeca,
  fontManrope,
  fontPoppins,
} from "@/utils/fonts";
import "./globals.css";
import MainLayout from "@/layout";
import "bootstrap/dist/css/bootstrap.min.css";
import StoreProvider from "@/redux/StoreProvider";

export const metadata = {
  title: "PayPay Hub",
  description: "Generated by create next app",
  icons: {
    apple: ["/apple.png"],
    chrome: ["chrome.png"],
  },
  manifest: "site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100..900&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>

      <body
        className={`${fontLato.variable} ${fontPoppins.variable} ${fontLexendDeca.variable} ${fontManrope.variable}`}
      >
        <StoreProvider>
          <MainLayout>{children}</MainLayout>
        </StoreProvider>
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
          integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
          integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
